# -*- coding: utf-8 -*-
"""Languagedetectionproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DubnsIWnUhV7WvkOAqg4zuoAZQS_ROEX
"""

import pandas
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report


data = pandas.read_csv("language.csv")


print(data.head())


def clean_text(text):
    text = re.sub(r'[^\w\s]', ' ', text)
    text = re.sub(r'\d+', ' ', text)
    text = text.lower().strip()
    return text


data.columns = ['text', 'language']


data['text'] = data['text'].apply(clean_text)


X = data['text']
y = data['language']


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


vectorizer = TfidfVectorizer(analyzer='char', ngram_range=(1, 3))

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)


model = MultinomialNB()
model.fit(X_train_tfidf, y_train)


y_pred = model.predict(X_test_tfidf)


accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

print("Classification Report:\n")
print(classification_report(y_test, y_pred))


def predict_language(text):
    text = clean_text(text)
    text_tfidf = vectorizer.transform([text])
    return model.predict(text_tfidf)[0]


print(predict_language("hello"))
print(predict_language("สวัสดี"))
print(predict_language("bonjour"))
print(predict_language("你好"))
print(predict_language("こんにちは"))
print(predict_language("인도"))

!pip freeze > requirements.txt